/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as SolveLaterRouteImport } from './routes/solve-later'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuizSubjectIdRouteImport } from './routes/quiz.$subjectId'

const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const SolveLaterRoute = SolveLaterRouteImport.update({
  id: '/solve-later',
  path: '/solve-later',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizSubjectIdRoute = QuizSubjectIdRouteImport.update({
  id: '/quiz/$subjectId',
  path: '/quiz/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/practice': typeof PracticeRoute
  '/solve-later': typeof SolveLaterRoute
  '/subjects': typeof SubjectsRoute
  '/quiz/$subjectId': typeof QuizSubjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/practice': typeof PracticeRoute
  '/solve-later': typeof SolveLaterRoute
  '/subjects': typeof SubjectsRoute
  '/quiz/$subjectId': typeof QuizSubjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/practice': typeof PracticeRoute
  '/solve-later': typeof SolveLaterRoute
  '/subjects': typeof SubjectsRoute
  '/quiz/$subjectId': typeof QuizSubjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/practice'
    | '/solve-later'
    | '/subjects'
    | '/quiz/$subjectId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/practice' | '/solve-later' | '/subjects' | '/quiz/$subjectId'
  id:
    | '__root__'
    | '/'
    | '/practice'
    | '/solve-later'
    | '/subjects'
    | '/quiz/$subjectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PracticeRoute: typeof PracticeRoute
  SolveLaterRoute: typeof SolveLaterRoute
  SubjectsRoute: typeof SubjectsRoute
  QuizSubjectIdRoute: typeof QuizSubjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solve-later': {
      id: '/solve-later'
      path: '/solve-later'
      fullPath: '/solve-later'
      preLoaderRoute: typeof SolveLaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$subjectId': {
      id: '/quiz/$subjectId'
      path: '/quiz/$subjectId'
      fullPath: '/quiz/$subjectId'
      preLoaderRoute: typeof QuizSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PracticeRoute: PracticeRoute,
  SolveLaterRoute: SolveLaterRoute,
  SubjectsRoute: SubjectsRoute,
  QuizSubjectIdRoute: QuizSubjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
